export type Row = Record<string, string | number>;

export interface MockData {
  headers: string[];
  rows: Row[];
}

export const mockData: MockData = {
  headers: [
    "OrderID",
    "CustomerID",
    "CustomerName",
    "Product",
    "Category",
    "Price",
    "OrderDate",
    "City",
    "Country",
    "Status",
  ],
  rows: [
    {
      "OrderID": 1001,
      "CustomerID": "C001",
      "CustomerName": "Alice Johnson",
      "Product": "Laptop",
      "Category": "Electronics",
      "Price": 1200,
      "OrderDate": "2023-01-15",
      "City": "New York",
      "Country": "USA",
      "Status": "Shipped",
    },
    {
      "OrderID": 1002,
      "CustomerID": "C002",
      "CustomerName": "Bob Smith",
      "Product": "Smartphone",
      "Category": "Electronics",
      "Price": 800,
      "OrderDate": "2023-01-17",
      "City": "Los Angeles",
      "Country": "USA",
      "Status": "Processing",
    },
    {
      "OrderID": 1003,
      "CustomerID": "C003",
      "CustomerName": "Charlie Brown",
      "Product": "Office Chair",
      "Category": "Furniture",
      "Price": 150,
      "OrderDate": "2023-01-20",
      "City": "London",
      "Country": "UK",
      "Status": "Delivered",
    },
    {
      "OrderID": 1004,
      "CustomerID": "C001",
      "CustomerName": "Alice Johnson",
      "Product": "Keyboard",
      "Category": "Electronics",
      "Price": 75,
      "OrderDate": "2023-02-10",
      "City": "New York",
      "Country": "USA",
      "Status": "Shipped",
    },
    {
      "OrderID": 1005,
      "CustomerID": "C004",
      "CustomerName": "Diana Miller",
      "Product": "Desk Lamp",
      "Category": "Furniture",
      "Price": 40,
      "OrderDate": "2023-02-12",
      "City": "Paris",
      "Country": "France",
      "Status": "Shipped",
    },
    {
      "OrderID": 1006,
      "CustomerID": "C005",
      "CustomerName": "Ethan Wilson",
      "Product": "Coffee Maker",
      "Category": "Home Appliances",
      "Price": 90,
      "OrderDate": "2023-02-22",
      "City": "Tokyo",
      "Country": "Japan",
      "Status": "Processing",
    },
    {
      "OrderID": 1007,
      "CustomerID": "C002",
      "CustomerName": "Bob Smith",
      "Product": "Headphones",
      "Category": "Electronics",
      "Price": 120,
      "OrderDate": "2023-03-01",
      "City": "Los Angeles",
      "Country": "USA",
      "Status": "Delivered",
    },
    {
      "OrderID": 1008,
      "CustomerID": "C003",
      "CustomerName": "Charlie Brown",
      "Product": "Bookshelf",
      "Category": "Furniture",
      "Price": 200,
      "OrderDate": "2023-03-05",
      "City": "London",
      "Country": "UK",
      "Status": "Shipped",
    },
    {
      "OrderID": 1009,
      "CustomerID": "C006",
      "CustomerName": "Fiona Davis",
      "Product": "Blender",
      "Category": "Home Appliances",
      "Price": 60,
      "OrderDate": "2023-03-15",
      "City": "Sydney",
      "Country": "Australia",
      "Status": "Processing",
    },
    {
      "OrderID": 1010,
      "CustomerID": "C001",
      "CustomerName": "Alice Johnson",
      "Product": "Mouse",
      "Category": "Electronics",
      "Price": 25,
      "OrderDate": "2023-04-02",
      "City": "New York",
      "Country": "USA",
      "Status": "Delivered",
    },
  ],
};
